import { Button, HStack } from "@chakra-ui/react";
import axios from "axios";
import Head from "next/head";

export default function Home() {
  const fc = async () => {
    try {
      const response = await axios.post("/api/hello");

      console.log(response);
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HStack w="full" justify={"center"}>
        <Button onClick={() => fc()}>Click me</Button>
      </HStack>
    </>
  );
}
